# Generated by Django 3.0 on 2020-06-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('register_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(max_length=12)),
                ('user_bdate', models.DateField()),
                ('user_password', models.CharField(max_length=50)),
                ('user_interested_in', models.CharField(choices=[('Mobile Apps', 'Mobile Apps'), ('Web Development', 'Web Development'), ('E-commerce', 'E-commerce'), ('UI /UX', 'UI /UX'), ('Digital Marketing', 'Digital Marketing'), ('Testing & Quality assurance', 'Testing & Quality assurance')], max_length=30)),
                ('user_city', models.CharField(max_length=50)),
                ('user_experience', models.CharField(choices=[('Fresher', 'Fresher'), ('Experienced', 'Experienced')], max_length=20)),
                ('nda', models.BooleanField(default=True, verbose_name='NDA')),
                ('user_image', models.ImageField(upload_to='')),
                ('resumefile', models.FileField(upload_to='')),
                ('addmin_note', models.TextField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
