# Generated by Django 2.2.7 on 2020-06-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateRegistrationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='register_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
